---
sidebar: sidebar 
permalink: concept-azure-netapp-files.html 
keywords: azure netapp files, cost, price, features, azure netapp files features, anf, supported regions, azure regions, azure netapp files regions 
summary: Azure NetApp Files permite a las empresas migrar y ejecutar sus aplicaciones esenciales para la empresa, sensibles a la latencia y con un alto rendimiento en Azure sin necesidad de refactorizar el cloud. 
---
= Más información sobre Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure NetApp Files permite a las empresas migrar y ejecutar sus aplicaciones esenciales para la empresa, sensibles a la latencia y con un alto rendimiento en Azure sin necesidad de refactorizar el cloud.



== Funciones

* La compatibilidad con varios protocolos permite que las aplicaciones de Linux y Windows se ejecuten sin problemas en Azure.
* Los múltiples niveles de rendimiento permiten alinear estrechamente con los requisitos de rendimiento de la carga de trabajo.
* Las certificaciones más importantes, como SAP HANA, GDPR e HIPAA, permiten la migración de las cargas de trabajo más exigentes a Azure.




== Características adicionales en BlueXP

* Migre datos de NFS o SMB a Azure NetApp Files directamente desde BlueXP (anteriormente Cloud Manager). Las migraciones de datos se realizan a través del servicio Cloud Sync de NetApp.
+
https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["Obtenga más información acerca de Cloud Sync"^]

* Con la tecnología impulsada por la inteligencia artificial (IA), Cloud Data Sense puede ayudarle a comprender el contexto de los datos e identificar los datos confidenciales que residen en sus cuentas de Azure NetApp Files.
+
https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["Más información acerca de Cloud Data Sense"^]





== Coste

https://azure.microsoft.com/pricing/details/netapp/["Ver los precios de Azure NetApp Files"^]

Tenga en cuenta que el servicio Azure NetApp Files y no BlueXP mantienen la suscripción y la carga.



== Regiones admitidas

https://cloud.netapp.com/cloud-volumes-global-regions["Consulte las regiones de Azure admitidas"^]



== Obtener ayuda

En el caso de los problemas de soporte técnico asociados con Azure NetApp Files, use el portal de Azure para registrar una solicitud de soporte a Microsoft. Seleccione su suscripción de Microsoft asociada y seleccione el nombre de servicio *Azure NetApp Files* en *almacenamiento*. Proporcione la información restante necesaria para crear su solicitud de soporte técnico de Microsoft.



== Enlaces relacionados

* https://cloud.netapp.com/azure-netapp-files["Sitio web de NetApp BlueXP: Azure NetApp Files"^]
* https://docs.microsoft.com/azure/azure-netapp-files/["Documentación de Azure NetApp Files"^]
* https://docs.netapp.com/us-en/cloud-manager-sync/index.html["Documentación de Cloud Sync"^]

