---
settings:
  name: Azure NetApp Files
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Documentos de Azure NetApp Files
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Más información sobre Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Inicio rápido
      url: "/task-quick-start.html"
    - title: Configure una aplicación de Azure AD
      url: "/task-set-up-azure-ad.html"
    - title: Crear un entorno de trabajo
      url: "/task-create-working-env.html"
  - title: Utilice Azure NetApp Files
    entries:
    - title: Cree y monte volúmenes
      url: "/task-create-volumes.html"
    - title: Gestione los volúmenes existentes
      url: "/task-manage-volumes.html"
    - title: Quite Azure NetApp Files
      url: "/task-remove-working-env.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Más información sobre Azure NetApp Files
      url: concept-azure-netapp-files.html
    - title: Inicio rápido
      url: task-quick-start.html
  - title: Utilice Azure NetApp Files
    links:
    - title: Cree volúmenes
      url: task-create-volumes.html
    - title: Gestione los volúmenes
      url: task-manage-volumes.html
  - title: Blogs y comunidad
    links:
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog de BlueXP
      url: https://cloud.netapp.com/blog
    - title: Seminarios web sobre el cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toda la documentación de BlueXP
